{% set name = "foxes" %}
{% set version = "1.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: 681aab1ecf40017b2baada761b5bda3fbb1fd4a1dcd0da181d70da6783b00657

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - foxes_yaml = foxes.input.yaml.yaml:main
    - foxes_windio = foxes.input.yaml.windio.windio:main
    - foxes_create_mean_dataset = foxes.input.states.create.dataset_mean:main
    - wrf2foxes = foxes.input.states.create.wrf2foxes:main
    - era52foxes = foxes.input.states.create.era52foxes:main
    - iconDream2foxes = foxes.input.states.create.icon_dream:main
    - eww2foxes = foxes.input.farm_layout.from_eww:main
    - foxes_create_gaussian_lookup = foxes.utils.create_gaussian_lookup:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=84
  run:
    - python >={{ python_min }},<3.14
    - matplotlib-base >=3.8
    - numpy >=1.26
    - pandas >=2.0
    - scipy >=1.12
    - xarray >=2023
    - netcdf4 >=1.6
    - h5netcdf >=1.8.1
    - h5py >=3.11.0
    - pyyaml >=6.0
    - tqdm >=4.31.1
    - utm >=0.5

test:
  imports:
    - foxes
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=7.0
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
    - foxes_yaml --help
    - foxes_windio --help
    - foxes_create_mean_dataset --help
    - wrf2foxes --help
    - era52foxes --help
    - iconDream2foxes --help
    - eww2foxes --help
    - foxes_create_gaussian_lookup --help

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox based on engineering wake models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
