{% set name = "foxes" %}
{% set version = "1.5.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: 64329c11e8530641aba51a7e636ec26b15fc3fdd464199226a306971599a4da4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - foxes_yaml = foxes.input.yaml.yaml:foxes_yaml
    - foxes_windio = foxes.input.yaml.windio.windio:foxes_windio

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8
    - numpy >=1.26
    - pandas >=2.0
    - xarray >=2023
    - scipy >=1.12
    - pyyaml >=4.0
    - cycler >=0.10
    - tqdm >=2.0

test:
  imports:
    - foxes
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=7.0
    - h5netcdf >=1.0
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox which is based on engineering wake models. It
    has many applications, for example wind farm optimization,
    wind farm post-construction analysis, wake model studies, and
    wind farm simulations invoking complex model chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
