{% set name = "foxes" %}
{% set version = "0.5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: 435e691f8c73e039c24571860d5c06f5ad8d554f46cf7b7e5a3cb2caff0af571

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - xarray
    - dask
    - scipy
    - plotly
    - iwopy
    - pyyaml
    - netcdf4

test:
  imports:
    - foxes
  requires:
    - pip
    - pytest
    - python-kaleido
    - pymoo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox which is based on engineering wake models. It
    has many applications, for example wind farm optimization,
    wind farm post-construction analysis, wake model studies, and
    wind farm simulations invoking complex model chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
